Missing ScryptParams bug
  File "create_public_key.py", line 15, in <module>
    key = SigningKey(salt, password)
TypeError: __init__() missing 1 required positional argument: 'scrypt_params'